### ISSUE TITLE
Update group proposal process or create new process for group votes

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/indexer#22]
## Summary

While working on the group proposals process, we realized we need to also index group votes. When a user views a historical proposal, they should also be able to view who voted, when they voted, and possibly a rationale for their vote.

## Proposal

~(1) Index group proposal votes at the block height we index the group proposal as part of the same process~
(2) Create a separate process for indexing votes that listens to `EventVote` and always stores the latest vote

*Note: The UI also includes the `weight` of the member that voted but this is neither stored in the proposal or the vote. We may want to reconsider whether this is necessary or revisit in a followup.*

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/indexer/22?planning-poker) with Zenhub @wgwz @ryanchristo

**Comment by blushi** [comment]
> Since we use `EventProposalPruned` for historical proposals, that means the voting period is closed. Since this task only cares about historical votes, then we really don't need to listen to `EventVote`. We only need to fetch state of the votes at the time of `EventProposalPruned`. Does this sound right? /cc @ryanchristo I think @blushi and I were missing this understanding when we spoke about this last.

Well it's possible that the votes gets pruned before the proposal does, so in order to handle this case, we need to listen to `EvenVote` I think, see some previous comment about that https://github.com/regen-network/groups-ui/pull/112#pullrequestreview-1549256008

**Comment by ryanchristo** [comment]
Sorry I missed this comment last week. Votes are pruned if (1) the proposal is aborted or withdrawn (2) votes are final (either all required votes have been cast or the voting period has expired). The block height will be different if the final vote does not also try to execute the proposal (immediately executing the proposal is an option when submitting the vote).

https://github.com/regen-network/cosmos-sdk/blob/main/x/group/keeper/keeper.go#L399

With that in mind, we should be listening for `EventVote` and checking whether the votes are final and then querying the votes at the block height prior to the votes being pruned. We could also update the votes as the events are emitted as long as we are taking into account that they will need to be updated if the voter changes their vote (i.e. a second event should update the one already stored rather than be ignored or adding a new vote, separate from indexing blocks, txs, msgs, etc).

**Comment by wgwz** [comment]
@ryanchristo @blushi thanks for the clarifying comments, that helps. 

re. the two approaches, i felt that the approach of extending the existing proposal process made sense if we could always reliably record the votes at the same time that `EventProposalPruned` gets handled. but since we can't do that, i think the separate process makes better sense.
