### ISSUE TITLE
Adjust heroku build to run migrations script

### ISSUE THREAD

**Issue by wgwz** [regen-network/indexer#24]
~~Pending completion of https://github.com/regen-network/indexer/issues/21 , adjust the heroku build process so that it runs the temporary migration script (`sql/run_all_migrations.sh`).~~

Instead of using the "temporary" `sql/run_all_migrations.sh` script, pending https://github.com/regen-network/indexer/issues/25, we can instead have the heroku build process use the postgraphile-migrate migrate command.

**Comment by ryanchristo** [comment]
@wgwz please update to align with #25. :pray:

**Comment by wgwz** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/indexer/24?planning-poker) with Zenhub @blushi @ryanchristo

**Comment by wgwz** [comment]
@ryanchristo @blushi updated the description!
