### ISSUE TITLE
Index credit classes issuers

### ISSUE THREAD

**Issue by blushi** [regen-network/indexer#30]
Currently in order to check that a user can issue credits, we need to make individual queries https://buf.build/regen/regen-ledger/docs/main:regen.ecocredit.v1#regen.ecocredit.v1.Query.ClassIssuers per credit class. This becomes very slow as soon as we have a large number of credit classes and impact the marketplace app performance (https://github.com/regen-network/rnd-dev-team/issues/1757, https://github.com/regen-network/regen-web/issues/2000).

We should index credit classes issuers in order to be able to make a single and performant query "get credit classes by issuer".

This can be implemented by listening to the events `regen.ecocredit.v1.EventCreateClass` and `regen.ecocredit.v1.EventUpdateClassIssuers` and maintaining entries in a `credit_classes` table with at least the credit class id and the issuer address as columns.

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/indexer/30?planning-poker) with Zenhub @ryanchristo @wgwz

**Comment by wgwz** [comment]
@blushi one thing that would be helpful to have written out in this task as well as the task for indexing project admins are the events that we could listen to, to implement this. this would help me getting an estimate 🙏

**Comment by ryanchristo** [comment]
`EventCreateClass` will be emitted when a new `ClassIssuer` will be created in state and `EventUpdateClassIssuers` will be emitted when class issuers changes (issuers are added or removed from a credit class and therefore a new `ClassIssuer` is created or an existing `ClassIssuer` is removed.

**Comment by ryanchristo** [comment]
`EventCreateClass` will be emitted when a new `ClassIssuer` is created in state and `EventUpdateClassIssuers` will be emitted when class issuers are added or removed from state (one or more `ClassIssuer` are created in state and/or one or more existing `ClassIssuer` are removed from state).

- `regen.ecocredit.v1.EventCreateClass`
- `regen.ecocredit.v1.EventUpdateClassIssuers`

**Comment by wgwz** [comment]
thanks @ryanchristo !
