### ISSUE TITLE
Set up indexer to enable improved filtering with allTxes query

### ISSUE THREAD

**Issue by wgwz** [regen-network/indexer#32]
We need to be able to write a graphql query that filters `allTxes` to successful txes as well as txes specific to a module.
Per architecture call today, we've identified a path forward to doing this.
- We want to enable the connection filter postgraphile plugin in regen-server for the indexer so that you can filter by fields in `jsonb` columns.
- We need to add database indexes to `tx.data` such that an `allTxes` graphql query remains reasonably performant.
- We will require an index on whichever field in `tx.data` indicates success
- The other index would be on whichever field in `tx.data` indicates a tx related to the ecocredit module

Side-note:
- indexes in jsonb columns can be done like so for a particular field: https://github.com/regen-network/indexer/blob/main/sql/V1__init.sql#L38
- See how the marketplace graphql postgraphile is configured for setting up the connection filter plugin: https://github.com/regen-network/regen-server/blob/dev/server/Server.ts#L200

**Comment by wgwz** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/indexer/32?planning-poker) with Zenhub @ryanchristo

**Comment by ryanchristo** [comment]
That's correct. If code does not equal zero (or is greater than zero).

**Comment by wgwz** [comment]
I just wanted to note that I discovered today that we do not need to index this path in `tx.data`:
```
data -> 'tx_response' -> 'tx' -> '@type'
```
Because that particular `@type` seems to always return `/cosmos.tx.v1beta1.Tx`.
I believe that instead we need to use `msg_event.type` from the indexer database to filter these.
