### ISSUE TITLE
Heroku database at capacity

### ISSUE THREAD

**Issue by wgwz** [regen-network/indexer#51]
The production indexer database is at capacity, we're on standard-2:
https://devcenter.heroku.com/articles/heroku-postgres-plans#standard-tier

Standard-2 price is $200/month for 256 GB max storage:
https://elements.heroku.com/addons/heroku-postgresql#standard-2

The next bump in the standard plan is standard-3, $400/month for 512 GB max storage:
https://elements.heroku.com/addons/heroku-postgresql#standard-3

This task is to research alternative options that may be cheaper as the database grows.
One discussed previously is AWS RDS, but there are other options as well.
I.e. https://www.crunchydata.com/products/crunchy-bridge (among many others)
crunchydata makes db management easier than aws, but still offers a competitive price point.

We need to decide where the database goes, how we migrate the database.
I.e. do we manually stop the indexer process, and do a manual migration to the new db using pgdump and pgrestore? and restart the indexer pointed at the new database once it's complete?

Alternatively, this task could choose the cost, and just bump to the $400/month plan.
Alternatively or additionally, we could look to filter out some data the indexer is capturing.
I.e. there's some kind of network health check ping that we are storing, and there's a lot of that and i doubt we care about indexing those.

**Comment by wgwz** [comment]
Also relevant to this and why it's important:
[#2046](https://github.com/regen-network/regen-web/issues/2046)

**Comment by wgwz** [comment]
For 512GB (double our current), and similar CPU/mem characteristics to our current heroku database, $191/month

![Screen Shot 2023-10-18 at 12 14 40 PM](https://github.com/regen-network/indexer/assets/10120306/690aea1f-cb3b-4e50-bbac-ff4f5b64d4c2)

https://www.crunchydata.com/pricing/calculator?provider=aws&region=us-east-1&tier=standard&plan=standard-8&storage=512

**Comment by aaronc** [comment]
How complex would a migration be?

**Comment by wgwz** [comment]
TODO: confirm that crunchydata has backups available

**Comment by blushi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RND-Dev-Team-5f8998bec8958d000f4609e2/issues/regen-network/indexer/51?planning-poker) with Zenhub @blushi @wgwz

**Comment by wgwz** [comment]
I spoke with the crunchydata customer service team today and they answered some of our questions:

- backups
    - they showed me the feature and how it works, we get daily backups for free, for up to 10-days
    - there's a way you can create your own manual backups
    - you can restore from your backups
    
- what are the migration steps for the larger databases?
    - this doc was shared: https://crunchydata.notion.site/Setup-Replica-from-Heroku-Customer-Overview-96fcac45388a45cca693186377f35233
    - migration steps for smaller db's here (main difference is speed):
        - https://docs.crunchybridge.com/how-to/heroku_dump_restore#steps-to-migrate-via-logical-backup
    
I also asked them these two questions, which they'll get back to me on:
- for both migration methods, rough estimates of how long it takes for 256gb?
- for both migration methods, can we leave the database up and running for reads, while the migration is taking place? (up to the point of cutting over)

i also got a brief tour of the UI and it has some nice features

**Comment by wgwz** [comment]
I got replies from the cruncydata team on these items:

> I also asked them these two questions, which they'll get back to me on:
> 
>     * for both migration methods, rough estimates of how long it takes for 256gb?

> > Standard caveats apply for replica-method. It could be 5 minutes if they don't have any indexes that need rebuilding. pg_dump is variable due to network consideration so it's hard to estimate but as a total guess I would have them plan for at least an hour, more or (maybe) less depending on the type of instance they select on Crunchy

> 
>     * for both migration methods, can we leave the database up and running for reads, while the migration is taking place? (up to the point of cutting over)
> 

> > Yes, but that's entirely on the customer. If they have writes sneaking in they will be lost.

**Comment by wgwz** [comment]
Upon deployment for us we need to update:
- DATABASE_URL in the indexer
- INDEXER_DATABASE_URL in regen-server

**Comment by wgwz** [comment]
@blushi i forgot to add a vote yesterday, i added my vote but it's a bit of cheat so it's already done now :-)
