### ISSUE TITLE
Remove sql/ folder

### ISSUE THREAD

**Issue by wgwz** [regen-network/indexer#53]
This should have been removed as part of https://github.com/regen-network/indexer/pull/45. It's just a folder that we were storing old migrations in. These are no longer needed.

**Comment by paul121** [comment]
Note: this `sql` folder and old migrations are currently used in other places. Before removing here, these other places should be updated to the current `graphile-migrate` approach for migrations.

I'm still familiarizing myself but noticed `sql/run_all_migrations.sh` is at least being used in the Docker setup for regen-web: https://github.com/regen-network/regen-web/blob/8789af04941afed2ed582912ff082d7c8ffb9512/docker/scripts/indexer_init.sh#L3-L5

**Comment by wgwz** [comment]
IIRC I think that is only place we're using it. FWIW - the indexer is pinned to a particular commit with regen-web though - https://github.com/regen-network/regen-web/blob/8789af04941afed2ed582912ff082d7c8ffb9512/docker/indexer.Dockerfile#L8C19-L8C59

Just to say that the regen-web setup wouldn't break immediately upon making this change.

**Comment by paul121** [comment]
Thanks @wgwz ! I just opened a PR to update this in regen-web: https://github.com/regen-network/regen-web/pull/2268
