### ISSUE TITLE
Ecocredit activity page is displaying duplicate events

### ISSUE THREAD

**Issue by ryanchristo** [regen-network/indexer#55]
**Describe the bug**

The [activity page](https://app.regen.network/stats/activity) is currently showing duplicates of all events.

**To Reproduce**

1. Go to https://app.regen.network/stats/activity and note duplicate rows for every event

**Expected behavior**

The activity page shows one row per event.

**Screenshots**

![Screenshot from 2023-10-26 14-15-21](https://github.com/regen-network/regen-web/assets/12519942/ec5e7b6d-0bb8-4133-9dd1-601088a647c4)

**Additional context**

I have not investigated the issue yet, but this might be an issue with the indexer.

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels and zenhub epics applied
- [ ] Appropriate contributors tagged

**Comment by blushi** [comment]
Looks like the query I updated in my indexer PR is not performant enough on the production db which is larger than the staging db, it takes ~50s which is way too much. Looking at `explain analyze` output, the index is not really being used with the LIKE operator on the jsonb column so I’m investigating how to improve this. So re-opening.
